apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "qlkube.fullname" . }}
  labels:
    {{- include "qlkube.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "qlkube.fullname" . }}
                port:
                  name: http
  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.secret }}
